version: "3.8"
services:
  client:
    build: ./client
    ports: 
      - 3000:3000
  server:
    build: ./
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/PortfolioApps
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: